# Generated by Django 3.0.5 on 2020-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
